# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
  - name: CV
    url: uploads/obradovic-vita.pdf
    weight: 20
  - name: Working Papers
    url: '#posts'
    weight: 30
  - name: Work in Progress
    url: '#projects'
    weight: 40
  - name: Publications
    url: '#featured'
    weight: 50

main_menu:
  # Display the navigation bar?
  enable: true
  # Align menu links: left (l), center (c), or right (r)
  align: l
  # Display your site title or `assets/media/logo*` image in the nav bar?
  show_logo: true
  # Show a language chooser (if you have translated your site content)?
  show_translations: true
  # If `show_translations` is enabled, do you wish to display the current language name?
  show_language: false
  # Let the user override the default light/dark mode of your theme?
  show_day_night: true
  # Let the user search from the nav bar?
  show_search: true
  # Attempt to automatically highlight the active menu link? Can be disabled for complex sites.
  highlight_active_link: true

